# Generated by Django 6.0.7 on 2026-07-11 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_identidad', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=50)),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.propietario')),
            ],
        ),
    ]
