# Generated by Django 6.0.7 on 2026-07-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrs/'),
        ),
    ]
