# Generated by Django 6.0.7 on 2026-07-12 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_vehiculo_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='id_propietario',
            new_name='propietario',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(default='Autorizado', max_length=50),
        ),
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id_codigo_qr', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, upload_to='qrs_dinamicos/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionQR',
            fields=[
                ('id_configuracion_qr', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_renovacion', models.IntegerField()),
                ('unidad_tiempo', models.CharField(default='minutos', max_length=20)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
