# Generated by Django 6.0.7 on 2026-07-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_rename_id_propietario_vehiculo_propietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoqr',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='codigoqr',
            name='fecha_expiracion',
            field=models.DateTimeField(),
        ),
    ]
