# Generated by Django 6.0.7 on 2026-07-11 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.vehiculo')),
            ],
        ),
    ]
